# $HOME/.config/alacritty/alacritty.toml
# by Declan Zevan 2025-05-03

[general]

import = [
  "~/.config/alacritty/vaporwave.toml"
]

[window]

opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 8.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"
