# $HOME/.config/alacritty/alacritty.toml
# by Declan Zevan 2025-05-03

[window]

opacity = 0.9

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[font]

normal.family = "MesloLGM Nerd Font Mono"
bold.family = "MesloLGM Nerd Font Mono"
italic.family = "MesloLGM Nerd Font Mono"
bold_italic.family = "MesloLGM Nerd Font Mono"

size = 8.0
